import type { ImageSourcePropType } from "react-native"

export const PREMIUM_FACE_PREVIEW_SOURCES: Readonly<
  Record<string, ImageSourcePropType>
> = {
  avatar_v2_eyes_mocha_doe: require("./assets/shop-thumbnails/avatar_v2_eyes_mocha_doe.png"),
  avatar_v2_eyes_sage_glass: require("./assets/shop-thumbnails/avatar_v2_eyes_sage_glass.png"),
  avatar_v2_eyes_twilight_plum: require("./assets/shop-thumbnails/avatar_v2_eyes_twilight_plum.png"),
  avatar_v2_eyes_hazel_almond_doe: require("./assets/shop-thumbnails/avatar_v2_eyes_hazel_almond_doe.png"),
  avatar_v2_eyes_deep_brown_star: require("./assets/shop-thumbnails/avatar_v2_eyes_deep_brown_star.png"),
  avatar_v2_eyes_cocoa_puppy: require("./assets/shop-thumbnails/avatar_v2_eyes_cocoa_puppy.png"),
  avatar_v2_eyes_honey_amber: require("./assets/shop-thumbnails/avatar_v2_eyes_honey_amber.png"),
  avatar_v2_eyes_chestnut_luminous: require("./assets/shop-thumbnails/avatar_v2_eyes_chestnut_luminous.png"),
  avatar_v2_nose_soft_button: require("./assets/shop-thumbnails/avatar_v2_nose_soft_button.png"),
  avatar_v2_nose_petal_curve: require("./assets/shop-thumbnails/avatar_v2_nose_petal_curve.png"),
  avatar_v2_nose_gentle_bridge: require("./assets/shop-thumbnails/avatar_v2_nose_gentle_bridge.png"),
  avatar_v2_nose_tiny_upturned: require("./assets/shop-thumbnails/avatar_v2_nose_tiny_upturned.png"),
  avatar_v2_nose_petite_rounded: require("./assets/shop-thumbnails/avatar_v2_nose_petite_rounded.png"),
  avatar_v2_nose_heart_tip: require("./assets/shop-thumbnails/avatar_v2_nose_heart_tip.png"),
  avatar_v2_nose_narrow_button: require("./assets/shop-thumbnails/avatar_v2_nose_narrow_button.png"),
  avatar_v2_nose_sculpted_doll: require("./assets/shop-thumbnails/avatar_v2_nose_sculpted_doll.png"),
  avatar_v2_mouth_peach_whisper_smile: require("./assets/shop-thumbnails/avatar_v2_mouth_peach_whisper_smile.png"),
  avatar_v2_mouth_rose_gloss_smile: require("./assets/shop-thumbnails/avatar_v2_mouth_rose_gloss_smile.png"),
  avatar_v2_mouth_berry_soft_kiss: require("./assets/shop-thumbnails/avatar_v2_mouth_berry_soft_kiss.png"),
  avatar_v2_mouth_coral_bow_smile: require("./assets/shop-thumbnails/avatar_v2_mouth_coral_bow_smile.png"),
  avatar_v2_mouth_nude_pink_whisper: require("./assets/shop-thumbnails/avatar_v2_mouth_nude_pink_whisper.png"),
  avatar_v2_mouth_cherry_balm_smile: require("./assets/shop-thumbnails/avatar_v2_mouth_cherry_balm_smile.png"),
  avatar_v2_mouth_soft_mauve_smile: require("./assets/shop-thumbnails/avatar_v2_mouth_soft_mauve_smile.png"),
  avatar_v2_mouth_rosewater_cupid_bow: require("./assets/shop-thumbnails/avatar_v2_mouth_rosewater_cupid_bow.png"),
  avatar_v2_hair_mocha_ribbon_blowout: require("./assets/shop-thumbnails/avatar_v2_hair_mocha_ribbon_blowout.png"),
  avatar_v2_hair_midnight_french_bob: require("./assets/shop-thumbnails/avatar_v2_hair_midnight_french_bob.png"),
  avatar_v2_hair_honey_halfup_waves: require("./assets/shop-thumbnails/avatar_v2_hair_honey_halfup_waves.png"),
  avatar_v2_hair_cherry_ribbon_twin_braids: require("./assets/shop-thumbnails/avatar_v2_hair_cherry_ribbon_twin_braids.png"),
  avatar_v2_hair_rosewood_butterfly_layers: require("./assets/shop-thumbnails/avatar_v2_hair_rosewood_butterfly_layers.png"),
  avatar_v2_hair_caramel_braided_crown: require("./assets/shop-thumbnails/avatar_v2_hair_caramel_braided_crown.png"),
  avatar_v2_hair_berry_velvet_soft_updo: require("./assets/shop-thumbnails/avatar_v2_hair_berry_velvet_soft_updo.png"),
  avatar_v2_hair_chestnut_butterfly_bob: require("./assets/shop-thumbnails/avatar_v2_hair_chestnut_butterfly_bob.png"),
  avatar_v2_hair_golden_waves: require("./assets/shop-thumbnails/avatar_v2_hair_golden_waves.png"),
  avatar_v2_hair_ink_pageboy_star: require("./assets/shop-thumbnails/avatar_v2_hair_ink_pageboy_star.png"),
  avatar_v2_hair_ink_twin_braids: require("./assets/shop-thumbnails/avatar_v2_hair_ink_twin_braids.png"),
  avatar_v2_hair_pale_golden_bow_bob: require("./assets/shop-thumbnails/avatar_v2_hair_pale_golden_bow_bob.png"),
  avatar_v2_hair_copper_bow_waves: require("./assets/shop-thumbnails/avatar_v2_hair_copper_bow_waves.png"),
  avatar_v2_face_warm_peach_foundation: require("./assets/shop-thumbnails/avatar_v2_face_warm_peach_foundation.png"),
  avatar_v2_face_rose_heart_foundation: require("./assets/shop-thumbnails/avatar_v2_face_rose_heart_foundation.png"),
  avatar_v2_accessory_rose_round_glasses: require("./assets/shop-thumbnails/avatar_v2_accessory_rose_round_glasses.png"),
  avatar_v2_accessory_lavender_pearl_cat_eye_glasses: require("./assets/shop-thumbnails/avatar_v2_accessory_lavender_pearl_cat_eye_glasses.png"),
  avatar_v2_accessory_mint_star_oval_glasses: require("./assets/shop-thumbnails/avatar_v2_accessory_mint_star_oval_glasses.png"),
  avatar_v2_accessory_honey_blossom_square_glasses: require("./assets/shop-thumbnails/avatar_v2_accessory_honey_blossom_square_glasses.png")
}
