export type MalePremiumCapsuleLayerType =
  "top" | "bottom" | "shoes" | "accessory" | "hairFront";
export type MalePremiumCapsuleAccessoryGroup =
  "headwear" | "eyewear" | "neck" | "bag";

export interface MalePremiumCapsuleItem {
  id: string;
  type: MalePremiumCapsuleLayerType;
  name: string;
  designBrief: string;
  palette: string;
  pilot: boolean;
  coordinationKey?: string;
  accessoryGroup?: MalePremiumCapsuleAccessoryGroup;
}

const item = (
  id: string,
  type: MalePremiumCapsuleLayerType,
  name: string,
  designBrief: string,
  palette: string,
  options: Pick<
    MalePremiumCapsuleItem,
    "pilot" | "coordinationKey" | "accessoryGroup"
  >,
): MalePremiumCapsuleItem => ({
  id,
  type,
  name,
  designBrief,
  palette,
  ...options,
});

export const MALE_PREMIUM_CAPSULE_INVENTORY: readonly MalePremiumCapsuleItem[] =
  [
    item(
      "tonal_geometric_camp_collar_shirt",
      "top",
      "Tonal Geometric Camp-Collar Shirt",
      "relaxed short sleeve camp collar with low contrast geometric panels and premium drape",
      "cocoa, cream, muted rust",
      { pilot: true },
    ),
    item(
      "asymmetric_utility_overshirt",
      "top",
      "Asymmetric Utility Overshirt",
      "boxy overshirt with original offset pockets and one restrained diagonal seam",
      "soft sage, charcoal",
      { pilot: false },
    ),
    item(
      "abstract_resort_shirt",
      "top",
      "Abstract Resort Shirt",
      "fluid short sleeve resort shirt with a small original abstract motif",
      "sunset clay, cream, dusty blue",
      { pilot: false },
    ),
    item(
      "charcoal_leather_bomber_hybrid",
      "top",
      "Charcoal Leather Bomber Hybrid",
      "relaxed leather bomber with subtle technical paneling and clean ribbing",
      "charcoal, graphite",
      { pilot: false },
    ),
    item(
      "wide_pleated_technical_trousers",
      "bottom",
      "Wide Pleated Technical Trousers",
      "controlled wide leg with technical pleats and quiet seam detail",
      "charcoal, dusty navy",
      { pilot: true },
    ),
    item(
      "straight_utility_tailored_trousers",
      "bottom",
      "Straight Utility-Tailored Trousers",
      "clean straight tailored cargo hybrid with minimal functional pockets",
      "warm gray, sage",
      { pilot: false },
    ),
    item(
      "midnight_relaxed_tailoring_jacket",
      "top",
      "Midnight Relaxed Tailoring Jacket",
      "soft shoulder double-breasted jacket with tonal evening-streetwear detail",
      "midnight navy",
      { pilot: true, coordinationKey: "midnight_relaxed_tailoring" },
    ),
    item(
      "midnight_relaxed_tailoring_trousers",
      "bottom",
      "Midnight Relaxed Tailoring Trousers",
      "matching wide straight tailoring trousers with restrained tonal seam detail",
      "midnight navy",
      { pilot: true, coordinationKey: "midnight_relaxed_tailoring" },
    ),
    item(
      "warm_sand_deconstructed_jacket",
      "top",
      "Warm Sand Deconstructed Jacket",
      "relaxed single-breasted jacket with original layered asymmetric construction",
      "warm sand, stone",
      { pilot: false, coordinationKey: "warm_sand_deconstructed_tailoring" },
    ),
    item(
      "warm_sand_deconstructed_trousers",
      "bottom",
      "Warm Sand Deconstructed Trousers",
      "matching clean straight trousers with a subtle layered waistband detail",
      "warm sand, stone",
      { pilot: false, coordinationKey: "warm_sand_deconstructed_tailoring" },
    ),
    item(
      "acid_washed_boxy_sweatshirt",
      "top",
      "Acid-Washed Boxy Sweatshirt",
      "boxy premium sweatshirt with original controlled acid wash and no text",
      "washed slate, charcoal",
      { pilot: true },
    ),
    item(
      "dusty_blue_weekend_crew_sweatshirt",
      "top",
      "Dusty Blue Weekend Crew Sweatshirt",
      "clean relaxed crew sweatshirt with a natural closed neckline and visible hands",
      "dusty blue, soft navy",
      { pilot: false },
    ),
    item(
      "modern_track_luxury_top",
      "top",
      "Modern Track-Luxury Top",
      "premium track jacket with a body-following collar and restrained curved paneling",
      "dusty navy, cream, cocoa",
      { pilot: false, coordinationKey: "modern_track_luxury" },
    ),
    item(
      "cocoa_sage_canvas_shacket",
      "top",
      "Cocoa Sage Canvas Shacket",
      "relaxed canvas shacket with a natural open neck and clean waist contact",
      "cocoa, soft sage",
      { pilot: false },
    ),
    item(
      "textured_knit_polo",
      "top",
      "Textured Knit Polo",
      "relaxed knit polo with tactile stitch texture, original collar and hem detail",
      "oat, cocoa",
      { pilot: false },
    ),
    item(
      "monochrome_street_tailoring_top",
      "top",
      "Monochrome Street Tailoring Top",
      "structured relaxed top with architectural tonal seams",
      "black, smoke, charcoal",
      { pilot: false, coordinationKey: "monochrome_street_tailoring" },
    ),
    item(
      "monochrome_street_tailoring_bottom",
      "bottom",
      "Monochrome Street Tailoring Trousers",
      "coordinated wide trousers with clean architectural seam language",
      "black, smoke, charcoal",
      { pilot: false, coordinationKey: "monochrome_street_tailoring" },
    ),
    item(
      "modern_track_luxury_bottom",
      "bottom",
      "Modern Track-Luxury Trousers",
      "coordinated relaxed track trousers with quiet diagonal paneling",
      "dusty navy, cream, cocoa",
      { pilot: false, coordinationKey: "modern_track_luxury" },
    ),
    item(
      "contemporary_resort_street_top",
      "top",
      "Contemporary Resort-Street Top",
      "relaxed short sleeve top with an original palm-shadow abstract motif",
      "warm sunset, sand, cocoa",
      { pilot: false, coordinationKey: "contemporary_resort_street" },
    ),
    item(
      "contemporary_resort_street_bottom",
      "bottom",
      "Contemporary Resort-Street Fluid Bottom",
      "coordinated fluid relaxed bottom with subtle motif trim",
      "warm sunset, sand, cocoa",
      { pilot: false, coordinationKey: "contemporary_resort_street" },
    ),
    item(
      "creative_utility_top",
      "top",
      "Creative Utility Overshirt",
      "boxy utility jacket with a refined pocket system",
      "forest, sand, terracotta",
      { pilot: false, coordinationKey: "creative_utility" },
    ),
    item(
      "creative_utility_bottom",
      "bottom",
      "Creative Utility Trousers",
      "coordinated utility trousers with controlled workwear pocket language",
      "forest, sand, terracotta",
      { pilot: false, coordinationKey: "creative_utility" },
    ),
    item(
      "relaxed_tailored_shorts",
      "bottom",
      "Relaxed Tailored Shorts",
      "clean pleated premium above-knee tailored shorts",
      "warm gray, cocoa",
      { pilot: false },
    ),
    item(
      "refined_utility_cargo_shorts",
      "bottom",
      "Refined Utility Cargo Shorts",
      "youthful cargo shorts with controlled pocket volume",
      "sage, warm sand",
      { pilot: false },
    ),
    item(
      "technical_sport_shorts",
      "bottom",
      "Premium Technical Sport Shorts",
      "soft nylon sport shorts with original elevated paneling",
      "graphite, dusty blue",
      { pilot: false },
    ),
    item(
      "soft_textured_crop",
      "hairFront",
      "Soft Textured Crop",
      "soft short crop with a clean natural hairline",
      "espresso brown",
      { pilot: true },
    ),
    item(
      "controlled_modern_mullet",
      "hairFront",
      "Controlled Modern Mullet",
      "short controlled crown with a subtle longer nape silhouette",
      "deep brown",
      { pilot: false },
    ),
    item(
      "voluminous_wavy_quiff",
      "hairFront",
      "Voluminous Wavy Quiff",
      "high but controlled wavy quiff with a clean forehead",
      "chestnut",
      { pilot: false },
    ),
    item(
      "short_twists_textured_style",
      "hairFront",
      "Short Twists Textured Style",
      "short defined twists with a distinct close-cropped silhouette",
      "rich umber",
      { pilot: false },
    ),
    item(
      "copper_compact_quiff",
      "hairFront",
      "Copper Compact Quiff",
      "compact brushed-back quiff with a natural canonical skull wrap",
      "copper auburn, cocoa lowlights",
      { pilot: false },
    ),
    item(
      "ash_blond_low_fade_crop",
      "hairFront",
      "Ash-Blond Textured Side Crop",
      "casual side-directed crop with tapered temples and a clean natural hairline",
      "cool ash blond, sand, beige gold",
      { pilot: false },
    ),
    item(
      "blue_black_short_curls",
      "hairFront",
      "Blue-Black Natural Wave Crop",
      "short off-center wave crop with controlled volume and open eye line",
      "deep blue black, charcoal, soft navy",
      { pilot: false },
    ),
    item(
      "retro_colorblock_runner",
      "shoes",
      "Retro Color-Block Runner",
      "cute retro running sneaker with cream mesh, powder-blue panels, muted coral accents, and a soft rounded sole",
      "cream, powder blue, muted coral",
      { pilot: false },
    ),
    item(
      "chunky_skate_sneakers",
      "shoes",
      "Chunky Skate Sneakers",
      "padded charcoal skate sneaker with soft lilac rubber details and a wide playful sole",
      "charcoal, lilac, cream",
      { pilot: false },
    ),
    item(
      "suede_penny_mules",
      "shoes",
      "Suede Penny Mules",
      "soft cocoa suede penny mules with rounded toe, tiny cream saddle stitching, and a cushioned sole",
      "cocoa, cream",
      { pilot: false },
    ),
    item(
      "lightweight_trail_sneakers",
      "shoes",
      "Lightweight Trail Sneakers",
      "light technical trail sneaker with powder-blue loop laces, warm stone mesh, and apricot accents",
      "warm stone, powder blue, apricot",
      { pilot: false },
    ),
    item(
      "soft_patch_beanie",
      "accessory",
      "Soft Patch Beanie",
      "soft lilac rib-knit beanie with an abstract non-lettered patch and rounded cuff",
      "lilac, oatmeal",
      { pilot: false, accessoryGroup: "headwear" },
    ),
    item(
      "nylon_crossbody_bag",
      "accessory",
      "Nylon Crossbody Bag",
      "compact powder-blue nylon crossbody with a wide cocoa diagonal strap and apricot zipper pull",
      "powder blue, cocoa, apricot",
      { pilot: false, accessoryGroup: "bag" },
    ),
    item(
      "beaded_charm_necklace",
      "accessory",
      "Beaded Charm Necklace",
      "short cream, lilac, and powder-blue beaded necklace with one tiny abstract star charm",
      "cream, lilac, powder blue",
      { pilot: false, accessoryGroup: "neck" },
    ),
    item(
      "tortoiseshell_smoke_sunglasses",
      "accessory",
      "Tortoiseshell Smoke Sunglasses",
      "complete slightly oversized smoke lenses with centered bridge and hair-tucked temples",
      "tortoiseshell, warm smoke, muted gold",
      { pilot: false, accessoryGroup: "eyewear" },
    ),
    item(
      "matte_black_panto_sunglasses",
      "accessory",
      "Matte Black Panto Sunglasses",
      "complete soft panto frame with slightly oversized lenses and compact temple fit",
      "matte black, charcoal smoke",
      { pilot: false, accessoryGroup: "eyewear" },
    ),
    item(
      "washed_baggy_denim",
      "bottom",
      "Washed Baggy Denim",
      "soft mid-blue relaxed baggy denim with subtle faded panels and small original stitch accents",
      "mid blue, indigo",
      { pilot: false },
    ),
    item(
      "soft_parachute_cargo_pants",
      "bottom",
      "Soft Parachute Cargo Pants",
      "warm-stone parachute cargo with powder-blue side pockets, cream drawcords, and gently gathered cuffs",
      "warm stone, powder blue, cream",
      { pilot: false },
    ),
    item(
      "colorblock_nylon_track_pants",
      "bottom",
      "Color-Block Nylon Track Pants",
      "relaxed charcoal nylon track pants with lilac, cream, and powder-blue color-block panels",
      "charcoal, lilac, cream, powder blue",
      { pilot: false },
    ),
    item(
      "striped_chunky_cardigan",
      "top",
      "Striped Chunky Cardigan",
      "soft knit cardigan with broad oatmeal, powder-blue, and muted lilac stripes and rounded buttons",
      "oatmeal, powder blue, lilac",
      { pilot: false },
    ),
    item(
      "colorblock_rugby_polo",
      "top",
      "Color-Block Rugby Polo",
      "relaxed street-prep rugby polo with dusty blue, warm cream, muted coral, and a soft white collar",
      "dusty blue, cream, coral",
      { pilot: false },
    ),
    item(
      "pixel_heart_boxy_tee",
      "top",
      "Pixel Heart Boxy Tee",
      "soft cream boxy tee with a tiny original pixel-heart motif and a lilac contrast collar",
      "cream, lilac, powder blue",
      { pilot: false },
    ),
    item(
      "soft_varsity_knit_jacket",
      "top",
      "Soft Varsity Knit Jacket",
      "cozy cocoa-and-powder-blue varsity knit jacket with rounded raglan sleeves and an abstract non-lettered patch",
      "cocoa, powder blue, cream",
      { pilot: false },
    ),
    item(
      "soft_panel_overshirt_bomber",
      "top",
      "Soft Panel Overshirt Bomber",
      "cute oatmeal overshirt-bomber hybrid with powder-blue sleeves, a muted coral placket, and one tiny original heart-star patch",
      "oatmeal, powder blue, muted coral",
      { pilot: false },
    ),
  ];
