import { StyleSheet } from "react-native"
import { uiTheme } from "../ui/theme"

export const wardrobeV2Styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: uiTheme.colors.background,
  },
  safe: {
    flex: 1,
  },
  screenBody: {
    flex: 1,
  },
  screenBodyContent: {
    flexGrow: 1,
  },
  screenBodyContentCompact: {
    paddingBottom: uiTheme.spacing.lg,
  },
  wardrobeFrame: {
    flex: 1,
    marginTop: uiTheme.spacing.sm,
    marginHorizontal: uiTheme.spacing.sm,
    borderRadius: 34,
    backgroundColor: "rgba(255,255,255,0.84)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.94)",
    overflow: "hidden",
    ...uiTheme.shadow.soft,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: uiTheme.spacing.md,
    paddingHorizontal: uiTheme.spacing.lg,
    paddingTop: uiTheme.spacing.sm,
    paddingBottom: uiTheme.spacing.sm,
  },
  iconButton: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F2DDEA",
  },
  iconButtonPressed: {
    opacity: 0.76,
    transform: [{ scale: 0.96 }],
  },
  titleBlock: {
    flex: 1,
  },
  title: {
    ...uiTheme.font.heading,
    color: uiTheme.colors.textPrimary,
  },
  subtitle: {
    ...uiTheme.font.caption,
    marginTop: 2,
    color: uiTheme.colors.textSecondary,
  },
  progressPill: {
    minWidth: 56,
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.82)",
    borderWidth: 1,
    borderColor: "#F2DDEA",
  },
  progressPillText: {
    ...uiTheme.font.captionBold,
    color: uiTheme.colors.textSecondary,
  },
  sectionSwitcher: {
    minHeight: 52,
    flexDirection: "row",
    gap: 6,
    marginHorizontal: uiTheme.spacing.lg,
    marginBottom: uiTheme.spacing.sm,
    padding: 4,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F2DDEA",
  },
  sectionButton: {
    flex: 1,
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    borderRadius: 14,
  },
  sectionButtonActive: {
    backgroundColor: uiTheme.colors.primary,
  },
  sectionButtonText: {
    ...uiTheme.font.captionBold,
    color: uiTheme.colors.textSecondary,
  },
  sectionButtonTextActive: {
    color: "#FFFFFF",
  },
  previewPanel: {
    paddingHorizontal: uiTheme.spacing.lg,
  },
  previewAndSlots: {
    minHeight: 286,
    flexDirection: "row",
    alignItems: "stretch",
    gap: uiTheme.spacing.sm,
  },
  previewAndSlotsCompact: {
    minHeight: 320,
  },
  avatarPreviewColumn: {
    flex: 1,
    minWidth: 0,
  },
  equippedSlotsRail: {
    width: 108,
    justifyContent: "space-between",
    paddingVertical: 2,
  },
  equippedSlotsRailCompact: {
    width: 116,
  },
  equippedSlot: {
    minHeight: 56,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 7,
    borderRadius: 18,
    backgroundColor: uiTheme.colors.glassStrong,
    borderWidth: 1,
    borderColor: uiTheme.colors.glassBorder,
    ...uiTheme.shadow.soft,
  },
  equippedSlotCompact: {
    minHeight: 62,
    paddingVertical: 5,
  },
  equippedSlotActive: {
    backgroundColor: "#FFF1F8",
    borderColor: uiTheme.colors.primary,
  },
  equippedSlotPressed: {
    opacity: 0.78,
  },
  equippedSlotPreview: {
    width: 46,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.78)",
    overflow: "hidden",
  },
  equippedSlotImage: {
    width: "100%",
    height: "100%",
  },
  equippedSlotLabel: {
    ...uiTheme.font.micro,
    flex: 1,
    color: uiTheme.colors.textSecondary,
    fontSize: 10,
    lineHeight: 12,
  },
  equippedSlotLabelActive: {
    color: uiTheme.colors.primaryDeep,
  },
  saveError: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: uiTheme.spacing.lg,
    marginTop: uiTheme.spacing.sm,
    paddingHorizontal: uiTheme.spacing.md,
    paddingVertical: uiTheme.spacing.sm,
    borderRadius: uiTheme.radius.lg,
    backgroundColor: "#FFF0F3",
    borderWidth: 1,
    borderColor: "#F7C8D2",
  },
  saveErrorText: {
    ...uiTheme.font.captionBold,
    flex: 1,
    color: uiTheme.colors.danger,
  },
  catalogShelf: {
    flex: 1,
    minHeight: 214,
    marginTop: uiTheme.spacing.sm,
  },
  categoryRow: {
    gap: 6,
    paddingHorizontal: uiTheme.spacing.lg,
    paddingBottom: 6,
  },
  bodySwitchHint: {
    ...uiTheme.font.caption,
    marginHorizontal: uiTheme.spacing.lg,
    marginBottom: 6,
    color: uiTheme.colors.textSecondary,
  },
  categoryTab: {
    minWidth: 72,
    minHeight: 40,
    borderRadius: uiTheme.radius.full,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: uiTheme.colors.glassStrong,
    borderWidth: 1,
    borderColor: "#F2DDEA",
  },
  categoryTabActive: {
    backgroundColor: uiTheme.colors.primary,
    borderColor: "rgba(255,255,255,0.2)",
  },
  categoryTabText: {
    ...uiTheme.font.captionBold,
    color: uiTheme.colors.textSecondary,
  },
  categoryTabTextActive: {
    color: "#FFFFFF",
  },
  carouselHeader: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: uiTheme.spacing.sm,
    paddingHorizontal: uiTheme.spacing.lg,
    paddingBottom: 5,
  },
  carouselTitle: {
    ...uiTheme.font.captionBold,
    flex: 1,
    minWidth: 0,
    color: uiTheme.colors.textPrimary,
  },
  carouselProgressTrack: {
    width: 82,
    height: 4,
    borderRadius: uiTheme.radius.full,
    backgroundColor: "#F1DDE8",
    overflow: "hidden",
  },
  carouselProgressThumb: {
    height: "100%",
    borderRadius: uiTheme.radius.full,
    backgroundColor: uiTheme.colors.primary,
  },
  carouselContent: {
    paddingHorizontal: uiTheme.spacing.lg,
    paddingBottom: uiTheme.spacing.sm,
  },
  carouselGap: {
    width: uiTheme.spacing.sm,
  },
  itemCard: {
    width: 148,
    minHeight: 164,
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 6,
    padding: 8,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F2DDEA",
    overflow: "hidden",
    ...uiTheme.shadow.float,
  },
  itemCardEquipped: {
    backgroundColor: "#FFF3FA",
    borderColor: uiTheme.colors.primary,
    shadowColor: "#FF4F98",
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  itemCardLocked: {
    opacity: 0.48,
  },
  itemCardPressed: {
    transform: [{ scale: 0.97 }],
  },
  itemPreviewStage: {
    position: "relative",
    width: "100%",
    height: 88,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
    backgroundColor: "#FFF2F8",
    overflow: "hidden",
  },
  itemPreviewHalo: {
    position: "absolute",
    bottom: 12,
    width: 78,
    height: 44,
    borderRadius: uiTheme.radius.full,
    backgroundColor: "#EAC3D9",
    opacity: 0.7,
  },
  itemPreviewSquare: {
    width: "100%",
    height: "100%",
    alignSelf: "center",
  },
  itemPreviewImage: {
    alignSelf: "center",
  },
  itemPreviewRigLayer: {
    ...StyleSheet.absoluteFill,
    width: "100%",
    height: "100%",
  },
  itemIconShell: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FFF7FB",
    borderWidth: 1,
    borderColor: "#F2DDEA",
  },
  itemIconShellEquipped: {
    backgroundColor: uiTheme.colors.primary,
  },
  itemCheckBadge: {
    position: "absolute",
    right: 8,
    top: 8,
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#31B67A",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.28)",
  },
  itemName: {
    ...uiTheme.font.bodySmall,
    fontSize: 13,
    lineHeight: 18,
    maxWidth: "100%",
    color: uiTheme.colors.textPrimary,
    fontWeight: "900",
    textAlign: "left",
  },
  itemMetaPill: {
    alignSelf: "flex-start",
    maxWidth: "100%",
    minHeight: 24,
    justifyContent: "center",
    paddingHorizontal: 8,
    borderRadius: uiTheme.radius.full,
    backgroundColor: uiTheme.colors.surfaceSoft,
    borderWidth: 1,
    borderColor: "#F4DDEB",
  },
  itemMetaPillEquipped: {
    backgroundColor: "#EFFFF7",
    borderColor: "#BFEEDB",
  },
  itemMeta: {
    ...uiTheme.font.captionBold,
    fontSize: 11,
    lineHeight: 14,
    maxWidth: "100%",
    color: uiTheme.colors.chipText,
    textAlign: "center",
  },
  itemMetaLocked: {
    opacity: 0.78,
  },
})
