import type {
  RoomV2AssetRef,
  RoomV2AvatarAssetSequence,
} from "../../roomV2/roomV2.types";

type Source = RoomV2AssetRef["source"];

const asset = (key: string, source: Source): RoomV2AssetRef => ({
  key,
  source,
});
const walking = (
  prefix: string,
  frames: readonly [Source, Source, Source, Source],
): RoomV2AvatarAssetSequence => ({
  frames: [
    asset(`${prefix}_walking_front_f01`, frames[0]),
    asset(`${prefix}_walking_front_f02`, frames[1]),
    asset(`${prefix}_walking_front_f03`, frames[2]),
    asset(`${prefix}_walking_front_f04`, frames[3]),
  ],
  frameDurationMs: 120,
  loop: true,
});
const clothingMotion = (
  prefix: string,
  frames: readonly [Source, Source, Source, Source],
  sitting: Source,
) => ({
  walkingFront: walking(prefix, frames),
  sittingFront: asset(`${prefix}_sitting_front_f01`, sitting),
});
const fixedHead = (prefix: string, source: Source) => ({
  walkingFront: walking(prefix, [source, source, source, source]),
  sittingFront: asset(`${prefix}_sitting_front_f01`, source),
});
const clothing = (
  type: "top" | "bottom" | "shoes",
  slug: string,
  f01: Source,
  f02: Source,
  f03: Source,
  f04: Source,
  sitting: Source,
) =>
  clothingMotion(
    `room_avatar_${type}_male_${slug}_v1`,
    [f01, f02, f03, f04],
    sitting,
  );

export const roomAvatarMalePremiumCapsuleLayerAssets = {
  tonal_geometric_camp_collar_shirt: asset(
    "avatar_room_top_male_tonal_geometric_camp_collar_shirt_v1",
    require("../assets/room/avatar_room_top_male_tonal_geometric_camp_collar_shirt_v1.png"),
  ),
  asymmetric_utility_overshirt: asset(
    "avatar_room_top_male_asymmetric_utility_overshirt_v1",
    require("../assets/room/avatar_room_top_male_asymmetric_utility_overshirt_v1.png"),
  ),
  abstract_resort_shirt: asset(
    "avatar_room_top_male_abstract_resort_shirt_v1",
    require("../assets/room/avatar_room_top_male_abstract_resort_shirt_v1.png"),
  ),
  cocoa_sage_canvas_shacket: asset(
    "avatar_room_top_male_cocoa_sage_canvas_shacket_v1",
    require("../assets/room/avatar_room_top_male_cocoa_sage_canvas_shacket_v1.png"),
  ),
  charcoal_leather_bomber_hybrid: asset(
    "avatar_room_top_male_charcoal_leather_bomber_hybrid_v1",
    require("../assets/room/avatar_room_top_male_charcoal_leather_bomber_hybrid_v1.png"),
  ),
  midnight_relaxed_tailoring_jacket: asset(
    "avatar_room_top_male_midnight_relaxed_tailoring_jacket_v1",
    require("../assets/room/avatar_room_top_male_midnight_relaxed_tailoring_jacket_v1.png"),
  ),
  warm_sand_deconstructed_jacket: asset(
    "avatar_room_top_male_warm_sand_deconstructed_jacket_v1",
    require("../assets/room/avatar_room_top_male_warm_sand_deconstructed_jacket_v1.png"),
  ),
  acid_washed_boxy_sweatshirt: asset(
    "avatar_room_top_male_acid_washed_boxy_sweatshirt_v1",
    require("../assets/room/avatar_room_top_male_acid_washed_boxy_sweatshirt_v1.png"),
  ),
  dusty_blue_weekend_crew_sweatshirt: asset(
    "avatar_room_top_male_dusty_blue_weekend_crew_sweatshirt_v1",
    require("../assets/room/avatar_room_top_male_dusty_blue_weekend_crew_sweatshirt_v1.png"),
  ),
  modern_track_luxury_top: asset(
    "avatar_room_top_male_modern_track_luxury_top_v1",
    require("../assets/room/avatar_room_top_male_modern_track_luxury_top_v1.png"),
  ),
  textured_knit_polo: asset(
    "avatar_room_top_male_textured_knit_polo_v1",
    require("../assets/room/avatar_room_top_male_textured_knit_polo_v1.png"),
  ),
  monochrome_street_tailoring_top: asset(
    "avatar_room_top_male_monochrome_street_tailoring_top_v1",
    require("../assets/room/avatar_room_top_male_monochrome_street_tailoring_top_v1.png"),
  ),
  contemporary_resort_street_top: asset(
    "avatar_room_top_male_contemporary_resort_street_top_v1",
    require("../assets/room/avatar_room_top_male_contemporary_resort_street_top_v1.png"),
  ),
  creative_utility_top: asset(
    "avatar_room_top_male_creative_utility_top_v1",
    require("../assets/room/avatar_room_top_male_creative_utility_top_v1.png"),
  ),
  wide_pleated_technical_trousers: asset(
    "avatar_room_bottom_male_wide_pleated_technical_trousers_v1",
    require("../assets/room/avatar_room_bottom_male_wide_pleated_technical_trousers_v1.png"),
  ),
  straight_utility_tailored_trousers: asset(
    "avatar_room_bottom_male_straight_utility_tailored_trousers_v1",
    require("../assets/room/avatar_room_bottom_male_straight_utility_tailored_trousers_v1.png"),
  ),
  midnight_relaxed_tailoring_trousers: asset(
    "avatar_room_bottom_male_midnight_relaxed_tailoring_trousers_v1",
    require("../assets/room/avatar_room_bottom_male_midnight_relaxed_tailoring_trousers_v1.png"),
  ),
  warm_sand_deconstructed_trousers: asset(
    "avatar_room_bottom_male_warm_sand_deconstructed_trousers_v1",
    require("../assets/room/avatar_room_bottom_male_warm_sand_deconstructed_trousers_v1.png"),
  ),
  monochrome_street_tailoring_bottom: asset(
    "avatar_room_bottom_male_monochrome_street_tailoring_bottom_v1",
    require("../assets/room/avatar_room_bottom_male_monochrome_street_tailoring_bottom_v1.png"),
  ),
  modern_track_luxury_bottom: asset(
    "avatar_room_bottom_male_modern_track_luxury_bottom_v1",
    require("../assets/room/avatar_room_bottom_male_modern_track_luxury_bottom_v1.png"),
  ),
  contemporary_resort_street_bottom: asset(
    "avatar_room_bottom_male_contemporary_resort_street_bottom_v1",
    require("../assets/room/avatar_room_bottom_male_contemporary_resort_street_bottom_v1.png"),
  ),
  creative_utility_bottom: asset(
    "avatar_room_bottom_male_creative_utility_bottom_v1",
    require("../assets/room/avatar_room_bottom_male_creative_utility_bottom_v1.png"),
  ),
  relaxed_tailored_shorts: asset(
    "avatar_room_bottom_male_relaxed_tailored_shorts_v1",
    require("../assets/room/avatar_room_bottom_male_relaxed_tailored_shorts_v1.png"),
  ),
  refined_utility_cargo_shorts: asset(
    "avatar_room_bottom_male_refined_utility_cargo_shorts_v1",
    require("../assets/room/avatar_room_bottom_male_refined_utility_cargo_shorts_v1.png"),
  ),
  technical_sport_shorts: asset(
    "avatar_room_bottom_male_technical_sport_shorts_v1",
    require("../assets/room/avatar_room_bottom_male_technical_sport_shorts_v1.png"),
  ),
  soft_textured_crop: asset(
    "avatar_room_hair_front_male_soft_textured_crop_v1",
    require("../assets/room/avatar_room_hair_front_male_soft_textured_crop_v1.png"),
  ),
  controlled_modern_mullet: asset(
    "avatar_room_hair_front_male_controlled_modern_mullet_v1",
    require("../assets/room/avatar_room_hair_front_male_controlled_modern_mullet_v1.png"),
  ),
  voluminous_wavy_quiff: asset(
    "avatar_room_hair_front_male_voluminous_wavy_quiff_v1",
    require("../assets/room/avatar_room_hair_front_male_voluminous_wavy_quiff_v1.png"),
  ),
  short_twists_textured_style: asset(
    "avatar_room_hair_front_male_short_twists_textured_style_v1",
    require("../assets/room/avatar_room_hair_front_male_short_twists_textured_style_v1.png"),
  ),
  copper_compact_quiff: asset(
    "avatar_room_hair_front_male_copper_compact_quiff_v1",
    require("../assets/room/avatar_room_hair_front_male_copper_compact_quiff_v1.png"),
  ),
  ash_blond_low_fade_crop: asset(
    "avatar_room_hair_front_male_ash_blond_low_fade_crop_v1",
    require("../assets/room/avatar_room_hair_front_male_ash_blond_low_fade_crop_v1.png"),
  ),
  blue_black_short_curls: asset(
    "avatar_room_hair_front_male_blue_black_short_curls_v1",
    require("../assets/room/avatar_room_hair_front_male_blue_black_short_curls_v1.png"),
  ),
  retro_colorblock_runner: asset(
    "avatar_room_shoes_male_retro_colorblock_runner_v1",
    require("../assets/room/avatar_room_shoes_male_retro_colorblock_runner_v1.png"),
  ),
  chunky_skate_sneakers: asset(
    "avatar_room_shoes_male_chunky_skate_sneakers_v1",
    require("../assets/room/avatar_room_shoes_male_chunky_skate_sneakers_v1.png"),
  ),
  suede_penny_mules: asset(
    "avatar_room_shoes_male_suede_penny_mules_v1",
    require("../assets/room/avatar_room_shoes_male_suede_penny_mules_v1.png"),
  ),
  lightweight_trail_sneakers: asset(
    "avatar_room_shoes_male_lightweight_trail_sneakers_v1",
    require("../assets/room/avatar_room_shoes_male_lightweight_trail_sneakers_v1.png"),
  ),
  soft_patch_beanie: asset(
    "avatar_room_accessory_male_soft_patch_beanie_v1",
    require("../assets/room/avatar_room_accessory_male_soft_patch_beanie_v1.png"),
  ),
  nylon_crossbody_bag: asset(
    "avatar_room_accessory_male_nylon_crossbody_bag_v1",
    require("../assets/room/avatar_room_accessory_male_nylon_crossbody_bag_v1.png"),
  ),
  beaded_charm_necklace: asset(
    "avatar_room_accessory_male_beaded_charm_necklace_v1",
    require("../assets/room/avatar_room_accessory_male_beaded_charm_necklace_v1.png"),
  ),
  tortoiseshell_smoke_sunglasses: asset(
    "avatar_room_accessory_male_tortoiseshell_smoke_sunglasses_v1",
    require("../assets/room/avatar_room_accessory_male_tortoiseshell_smoke_sunglasses_v1.png"),
  ),
  matte_black_panto_sunglasses: asset(
    "avatar_room_accessory_male_matte_black_panto_sunglasses_v1",
    require("../assets/room/avatar_room_accessory_male_matte_black_panto_sunglasses_v1.png"),
  ),
  washed_baggy_denim: asset(
    "avatar_room_bottom_male_washed_baggy_denim_v1",
    require("../assets/room/avatar_room_bottom_male_washed_baggy_denim_v1.png"),
  ),
  soft_parachute_cargo_pants: asset(
    "avatar_room_bottom_male_soft_parachute_cargo_pants_v1",
    require("../assets/room/avatar_room_bottom_male_soft_parachute_cargo_pants_v1.png"),
  ),
  colorblock_nylon_track_pants: asset(
    "avatar_room_bottom_male_colorblock_nylon_track_pants_v1",
    require("../assets/room/avatar_room_bottom_male_colorblock_nylon_track_pants_v1.png"),
  ),
  striped_chunky_cardigan: asset(
    "avatar_room_top_male_striped_chunky_cardigan_v1",
    require("../assets/room/avatar_room_top_male_striped_chunky_cardigan_v1.png"),
  ),
  colorblock_rugby_polo: asset(
    "avatar_room_top_male_colorblock_rugby_polo_v1",
    require("../assets/room/avatar_room_top_male_colorblock_rugby_polo_v1.png"),
  ),
  pixel_heart_boxy_tee: asset(
    "avatar_room_top_male_pixel_heart_boxy_tee_v1",
    require("../assets/room/avatar_room_top_male_pixel_heart_boxy_tee_v1.png"),
  ),
  soft_varsity_knit_jacket: asset(
    "avatar_room_top_male_soft_varsity_knit_jacket_v1",
    require("../assets/room/avatar_room_top_male_soft_varsity_knit_jacket_v1.png"),
  ),
  soft_panel_overshirt_bomber: asset(
    "avatar_room_top_male_soft_panel_overshirt_bomber_v1",
    require("../assets/room/avatar_room_top_male_soft_panel_overshirt_bomber_v1.png"),
  ),
} as const;

export const roomAvatarMalePremiumCapsuleMotionAssets = {
  tonal_geometric_camp_collar_shirt: clothing(
    "top",
    "tonal_geometric_camp_collar_shirt",
    require("../assets/room/motion/room_avatar_top_male_tonal_geometric_camp_collar_shirt_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_tonal_geometric_camp_collar_shirt_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_tonal_geometric_camp_collar_shirt_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_tonal_geometric_camp_collar_shirt_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_tonal_geometric_camp_collar_shirt_v1_sitting_front_f01.png"),
  ),
  asymmetric_utility_overshirt: clothing(
    "top",
    "asymmetric_utility_overshirt",
    require("../assets/room/motion/room_avatar_top_male_asymmetric_utility_overshirt_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_asymmetric_utility_overshirt_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_asymmetric_utility_overshirt_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_asymmetric_utility_overshirt_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_asymmetric_utility_overshirt_v1_sitting_front_f01.png"),
  ),
  abstract_resort_shirt: clothing(
    "top",
    "abstract_resort_shirt",
    require("../assets/room/motion/room_avatar_top_male_abstract_resort_shirt_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_abstract_resort_shirt_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_abstract_resort_shirt_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_abstract_resort_shirt_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_abstract_resort_shirt_v1_sitting_front_f01.png"),
  ),
  cocoa_sage_canvas_shacket: clothing(
    "top",
    "cocoa_sage_canvas_shacket",
    require("../assets/room/motion/room_avatar_top_male_cocoa_sage_canvas_shacket_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_cocoa_sage_canvas_shacket_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_cocoa_sage_canvas_shacket_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_cocoa_sage_canvas_shacket_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_cocoa_sage_canvas_shacket_v1_sitting_front_f01.png"),
  ),
  charcoal_leather_bomber_hybrid: clothing(
    "top",
    "charcoal_leather_bomber_hybrid",
    require("../assets/room/motion/room_avatar_top_male_charcoal_leather_bomber_hybrid_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_charcoal_leather_bomber_hybrid_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_charcoal_leather_bomber_hybrid_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_charcoal_leather_bomber_hybrid_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_charcoal_leather_bomber_hybrid_v1_sitting_front_f01.png"),
  ),
  midnight_relaxed_tailoring_jacket: clothing(
    "top",
    "midnight_relaxed_tailoring_jacket",
    require("../assets/room/motion/room_avatar_top_male_midnight_relaxed_tailoring_jacket_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_midnight_relaxed_tailoring_jacket_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_midnight_relaxed_tailoring_jacket_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_midnight_relaxed_tailoring_jacket_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_midnight_relaxed_tailoring_jacket_v1_sitting_front_f01.png"),
  ),
  warm_sand_deconstructed_jacket: clothing(
    "top",
    "warm_sand_deconstructed_jacket",
    require("../assets/room/motion/room_avatar_top_male_warm_sand_deconstructed_jacket_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_warm_sand_deconstructed_jacket_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_warm_sand_deconstructed_jacket_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_warm_sand_deconstructed_jacket_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_warm_sand_deconstructed_jacket_v1_sitting_front_f01.png"),
  ),
  acid_washed_boxy_sweatshirt: clothing(
    "top",
    "acid_washed_boxy_sweatshirt",
    require("../assets/room/motion/room_avatar_top_male_acid_washed_boxy_sweatshirt_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_acid_washed_boxy_sweatshirt_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_acid_washed_boxy_sweatshirt_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_acid_washed_boxy_sweatshirt_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_acid_washed_boxy_sweatshirt_v1_sitting_front_f01.png"),
  ),
  dusty_blue_weekend_crew_sweatshirt: clothing(
    "top",
    "dusty_blue_weekend_crew_sweatshirt",
    require("../assets/room/motion/room_avatar_top_male_dusty_blue_weekend_crew_sweatshirt_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_dusty_blue_weekend_crew_sweatshirt_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_dusty_blue_weekend_crew_sweatshirt_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_dusty_blue_weekend_crew_sweatshirt_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_dusty_blue_weekend_crew_sweatshirt_v1_sitting_front_f01.png"),
  ),
  modern_track_luxury_top: clothing(
    "top",
    "modern_track_luxury_top",
    require("../assets/room/motion/room_avatar_top_male_modern_track_luxury_top_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_modern_track_luxury_top_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_modern_track_luxury_top_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_modern_track_luxury_top_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_modern_track_luxury_top_v1_sitting_front_f01.png"),
  ),
  textured_knit_polo: clothing(
    "top",
    "textured_knit_polo",
    require("../assets/room/motion/room_avatar_top_male_textured_knit_polo_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_textured_knit_polo_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_textured_knit_polo_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_textured_knit_polo_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_textured_knit_polo_v1_sitting_front_f01.png"),
  ),
  monochrome_street_tailoring_top: clothing(
    "top",
    "monochrome_street_tailoring_top",
    require("../assets/room/motion/room_avatar_top_male_monochrome_street_tailoring_top_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_monochrome_street_tailoring_top_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_monochrome_street_tailoring_top_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_monochrome_street_tailoring_top_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_monochrome_street_tailoring_top_v1_sitting_front_f01.png"),
  ),
  contemporary_resort_street_top: clothing(
    "top",
    "contemporary_resort_street_top",
    require("../assets/room/motion/room_avatar_top_male_contemporary_resort_street_top_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_contemporary_resort_street_top_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_contemporary_resort_street_top_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_contemporary_resort_street_top_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_contemporary_resort_street_top_v1_sitting_front_f01.png"),
  ),
  creative_utility_top: clothing(
    "top",
    "creative_utility_top",
    require("../assets/room/motion/room_avatar_top_male_creative_utility_top_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_creative_utility_top_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_creative_utility_top_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_creative_utility_top_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_creative_utility_top_v1_sitting_front_f01.png"),
  ),
  wide_pleated_technical_trousers: clothing(
    "bottom",
    "wide_pleated_technical_trousers",
    require("../assets/room/motion/room_avatar_bottom_male_wide_pleated_technical_trousers_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_wide_pleated_technical_trousers_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_wide_pleated_technical_trousers_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_wide_pleated_technical_trousers_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_wide_pleated_technical_trousers_v1_sitting_front_f01.png"),
  ),
  straight_utility_tailored_trousers: clothing(
    "bottom",
    "straight_utility_tailored_trousers",
    require("../assets/room/motion/room_avatar_bottom_male_straight_utility_tailored_trousers_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_straight_utility_tailored_trousers_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_straight_utility_tailored_trousers_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_straight_utility_tailored_trousers_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_straight_utility_tailored_trousers_v1_sitting_front_f01.png"),
  ),
  midnight_relaxed_tailoring_trousers: clothing(
    "bottom",
    "midnight_relaxed_tailoring_trousers",
    require("../assets/room/motion/room_avatar_bottom_male_midnight_relaxed_tailoring_trousers_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_midnight_relaxed_tailoring_trousers_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_midnight_relaxed_tailoring_trousers_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_midnight_relaxed_tailoring_trousers_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_midnight_relaxed_tailoring_trousers_v1_sitting_front_f01.png"),
  ),
  warm_sand_deconstructed_trousers: clothing(
    "bottom",
    "warm_sand_deconstructed_trousers",
    require("../assets/room/motion/room_avatar_bottom_male_warm_sand_deconstructed_trousers_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_warm_sand_deconstructed_trousers_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_warm_sand_deconstructed_trousers_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_warm_sand_deconstructed_trousers_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_warm_sand_deconstructed_trousers_v1_sitting_front_f01.png"),
  ),
  monochrome_street_tailoring_bottom: clothing(
    "bottom",
    "monochrome_street_tailoring_bottom",
    require("../assets/room/motion/room_avatar_bottom_male_monochrome_street_tailoring_bottom_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_monochrome_street_tailoring_bottom_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_monochrome_street_tailoring_bottom_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_monochrome_street_tailoring_bottom_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_monochrome_street_tailoring_bottom_v1_sitting_front_f01.png"),
  ),
  modern_track_luxury_bottom: clothing(
    "bottom",
    "modern_track_luxury_bottom",
    require("../assets/room/motion/room_avatar_bottom_male_modern_track_luxury_bottom_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_modern_track_luxury_bottom_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_modern_track_luxury_bottom_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_modern_track_luxury_bottom_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_modern_track_luxury_bottom_v1_sitting_front_f01.png"),
  ),
  contemporary_resort_street_bottom: clothing(
    "bottom",
    "contemporary_resort_street_bottom",
    require("../assets/room/motion/room_avatar_bottom_male_contemporary_resort_street_bottom_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_contemporary_resort_street_bottom_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_contemporary_resort_street_bottom_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_contemporary_resort_street_bottom_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_contemporary_resort_street_bottom_v1_sitting_front_f01.png"),
  ),
  creative_utility_bottom: clothing(
    "bottom",
    "creative_utility_bottom",
    require("../assets/room/motion/room_avatar_bottom_male_creative_utility_bottom_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_creative_utility_bottom_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_creative_utility_bottom_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_creative_utility_bottom_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_creative_utility_bottom_v1_sitting_front_f01.png"),
  ),
  relaxed_tailored_shorts: clothing(
    "bottom",
    "relaxed_tailored_shorts",
    require("../assets/room/motion/room_avatar_bottom_male_relaxed_tailored_shorts_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_relaxed_tailored_shorts_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_relaxed_tailored_shorts_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_relaxed_tailored_shorts_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_relaxed_tailored_shorts_v1_sitting_front_f01.png"),
  ),
  refined_utility_cargo_shorts: clothing(
    "bottom",
    "refined_utility_cargo_shorts",
    require("../assets/room/motion/room_avatar_bottom_male_refined_utility_cargo_shorts_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_refined_utility_cargo_shorts_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_refined_utility_cargo_shorts_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_refined_utility_cargo_shorts_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_refined_utility_cargo_shorts_v1_sitting_front_f01.png"),
  ),
  technical_sport_shorts: clothing(
    "bottom",
    "technical_sport_shorts",
    require("../assets/room/motion/room_avatar_bottom_male_technical_sport_shorts_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_technical_sport_shorts_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_technical_sport_shorts_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_technical_sport_shorts_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_technical_sport_shorts_v1_sitting_front_f01.png"),
  ),
  retro_colorblock_runner: clothing(
    "shoes",
    "retro_colorblock_runner",
    require("../assets/room/motion/room_avatar_shoes_male_retro_colorblock_runner_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_shoes_male_retro_colorblock_runner_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_shoes_male_retro_colorblock_runner_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_shoes_male_retro_colorblock_runner_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_shoes_male_retro_colorblock_runner_v1_sitting_front_f01.png"),
  ),
  chunky_skate_sneakers: clothing(
    "shoes",
    "chunky_skate_sneakers",
    require("../assets/room/motion/room_avatar_shoes_male_chunky_skate_sneakers_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_shoes_male_chunky_skate_sneakers_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_shoes_male_chunky_skate_sneakers_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_shoes_male_chunky_skate_sneakers_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_shoes_male_chunky_skate_sneakers_v1_sitting_front_f01.png"),
  ),
  suede_penny_mules: clothing(
    "shoes",
    "suede_penny_mules",
    require("../assets/room/motion/room_avatar_shoes_male_suede_penny_mules_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_shoes_male_suede_penny_mules_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_shoes_male_suede_penny_mules_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_shoes_male_suede_penny_mules_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_shoes_male_suede_penny_mules_v1_sitting_front_f01.png"),
  ),
  lightweight_trail_sneakers: clothing(
    "shoes",
    "lightweight_trail_sneakers",
    require("../assets/room/motion/room_avatar_shoes_male_lightweight_trail_sneakers_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_shoes_male_lightweight_trail_sneakers_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_shoes_male_lightweight_trail_sneakers_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_shoes_male_lightweight_trail_sneakers_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_shoes_male_lightweight_trail_sneakers_v1_sitting_front_f01.png"),
  ),
  washed_baggy_denim: clothing(
    "bottom",
    "washed_baggy_denim",
    require("../assets/room/motion/room_avatar_bottom_male_washed_baggy_denim_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_washed_baggy_denim_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_washed_baggy_denim_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_washed_baggy_denim_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_washed_baggy_denim_v1_sitting_front_f01.png"),
  ),
  soft_parachute_cargo_pants: clothing(
    "bottom",
    "soft_parachute_cargo_pants",
    require("../assets/room/motion/room_avatar_bottom_male_soft_parachute_cargo_pants_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_soft_parachute_cargo_pants_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_soft_parachute_cargo_pants_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_soft_parachute_cargo_pants_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_soft_parachute_cargo_pants_v1_sitting_front_f01.png"),
  ),
  colorblock_nylon_track_pants: clothing(
    "bottom",
    "colorblock_nylon_track_pants",
    require("../assets/room/motion/room_avatar_bottom_male_colorblock_nylon_track_pants_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_bottom_male_colorblock_nylon_track_pants_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_bottom_male_colorblock_nylon_track_pants_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_bottom_male_colorblock_nylon_track_pants_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_bottom_male_colorblock_nylon_track_pants_v1_sitting_front_f01.png"),
  ),
  striped_chunky_cardigan: clothing(
    "top",
    "striped_chunky_cardigan",
    require("../assets/room/motion/room_avatar_top_male_striped_chunky_cardigan_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_striped_chunky_cardigan_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_striped_chunky_cardigan_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_striped_chunky_cardigan_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_striped_chunky_cardigan_v1_sitting_front_f01.png"),
  ),
  colorblock_rugby_polo: clothing(
    "top",
    "colorblock_rugby_polo",
    require("../assets/room/motion/room_avatar_top_male_colorblock_rugby_polo_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_colorblock_rugby_polo_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_colorblock_rugby_polo_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_colorblock_rugby_polo_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_colorblock_rugby_polo_v1_sitting_front_f01.png"),
  ),
  pixel_heart_boxy_tee: clothing(
    "top",
    "pixel_heart_boxy_tee",
    require("../assets/room/motion/room_avatar_top_male_pixel_heart_boxy_tee_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_pixel_heart_boxy_tee_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_pixel_heart_boxy_tee_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_pixel_heart_boxy_tee_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_pixel_heart_boxy_tee_v1_sitting_front_f01.png"),
  ),
  soft_varsity_knit_jacket: clothing(
    "top",
    "soft_varsity_knit_jacket",
    require("../assets/room/motion/room_avatar_top_male_soft_varsity_knit_jacket_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_soft_varsity_knit_jacket_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_soft_varsity_knit_jacket_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_soft_varsity_knit_jacket_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_soft_varsity_knit_jacket_v1_sitting_front_f01.png"),
  ),
  soft_panel_overshirt_bomber: clothing(
    "top",
    "soft_panel_overshirt_bomber",
    require("../assets/room/motion/room_avatar_top_male_soft_panel_overshirt_bomber_v1_walking_front_f01.png"),
    require("../assets/room/motion/room_avatar_top_male_soft_panel_overshirt_bomber_v1_walking_front_f02.png"),
    require("../assets/room/motion/room_avatar_top_male_soft_panel_overshirt_bomber_v1_walking_front_f03.png"),
    require("../assets/room/motion/room_avatar_top_male_soft_panel_overshirt_bomber_v1_walking_front_f04.png"),
    require("../assets/room/motion/room_avatar_top_male_soft_panel_overshirt_bomber_v1_sitting_front_f01.png"),
  ),
  soft_patch_beanie: fixedHead(
    "room_avatar_accessory_male_soft_patch_beanie_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.soft_patch_beanie.source,
  ),
  nylon_crossbody_bag: fixedHead(
    "room_avatar_accessory_male_nylon_crossbody_bag_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.nylon_crossbody_bag.source,
  ),
  beaded_charm_necklace: fixedHead(
    "room_avatar_accessory_male_beaded_charm_necklace_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.beaded_charm_necklace.source,
  ),
  tortoiseshell_smoke_sunglasses: fixedHead(
    "room_avatar_accessory_male_tortoiseshell_smoke_sunglasses_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.tortoiseshell_smoke_sunglasses.source,
  ),
  matte_black_panto_sunglasses: fixedHead(
    "room_avatar_accessory_male_matte_black_panto_sunglasses_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.matte_black_panto_sunglasses.source,
  ),
  soft_textured_crop: fixedHead(
    "room_avatar_hair_front_male_soft_textured_crop_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.soft_textured_crop.source,
  ),
  controlled_modern_mullet: fixedHead(
    "room_avatar_hair_front_male_controlled_modern_mullet_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.controlled_modern_mullet.source,
  ),
  voluminous_wavy_quiff: fixedHead(
    "room_avatar_hair_front_male_voluminous_wavy_quiff_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.voluminous_wavy_quiff.source,
  ),
  short_twists_textured_style: fixedHead(
    "room_avatar_hair_front_male_short_twists_textured_style_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.short_twists_textured_style.source,
  ),
  copper_compact_quiff: fixedHead(
    "room_avatar_hair_front_male_copper_compact_quiff_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.copper_compact_quiff.source,
  ),
  ash_blond_low_fade_crop: fixedHead(
    "room_avatar_hair_front_male_ash_blond_low_fade_crop_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.ash_blond_low_fade_crop.source,
  ),
  blue_black_short_curls: fixedHead(
    "room_avatar_hair_front_male_blue_black_short_curls_v1",
    roomAvatarMalePremiumCapsuleLayerAssets.blue_black_short_curls.source,
  ),
} as const;
