// Generated by scripts/build-room-motion-atlases.mjs. Do not edit.
// Index i is the image of atlases[i] in roomAvatarMotionAtlas.json.
import type { ImageSourcePropType } from "react-native"

export const ROOM_AVATAR_MOTION_ATLAS_SOURCES: readonly ImageSourcePropType[] = [
  require("../assets/room/motion-atlas/room_motion_atlas_female_accessory_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_female_base_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_female_bottom_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_female_eyes_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_female_face_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_female_hair_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_female_mouth_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_female_nose_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_female_shoes_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_female_top_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_male_base_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_male_bottom_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_male_shoes_01.png"),
  require("../assets/room/motion-atlas/room_motion_atlas_male_top_01.png")
]
